@baseURL = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhZG1pbkBpZnJzLmVkdS5iciIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4Mjg0NDUwMSwiZXhwIjoxNzgyODQ4MTAxfQ.q__43cBnAF23dRLRIObeU3Qpo2SDePGRARFAc2FtGCk


### Lista de pets disponíveis para adoção
GET {{baseURL}}/public/pets/available
Content-Type: application/json

###
POST {{baseURL}}/auth/users
Content-Type: application/json

{
  "name": "edu",
  "email": "edu@ifrs.edu.br",
  "password": "senha123",
  "phone": "123456789"
}

###
POST {{baseURL}}/auth/login
Content-Type: application/json

{
    "email": "admin@ifrs.edu.br",
    "password": "senha123"
}


### Acesso à área admin (rota protegida, requer token de usuário com role "admin")
GET {{baseURL}}/protected/users
Authorization: Bearer {{token}}

### usuário por ID
GET {{baseURL}}/protected/users/1
Authorization: Bearer {{token}}

### Atualizar usuário
PUT {{baseURL}}/protected/users/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Nome Atualizado",
  "email": "email@atualizado.com",
  "phone": "54988888888",
  "password": "senha2"
}

### deletar usuário
DELETE {{baseURL}}/protected/users/1
Authorization: Bearer {{token}}

### Listar pets
GET {{baseURL}}/protected/pets
Authorization: Bearer {{token}}

### Get pet by ID
GET {{baseURL}}/protected/pets/1
Authorization: Bearer {{token}}

### Criar pet
POST {{baseURL}}/protected/pets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Bolt",
  "age": 2,
  "species": "Cachorro",
  "size": "medium",
  "status": "available",
  "description": "Muito dócil"
}

### Atualizar pet
PUT {{baseURL}}/protected/pets/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Faree",
  "age": 2,
  "species": "Cachorro",
  "size": "medium",
  "status": "adopted",
  "description": "Muito dócil"
}

### Delete pet
DELETE {{baseURL}}/protected/pets/1
Authorization: Bearer {{token}}

### Listar adoções
GET {{baseURL}}/protected/adoptions
Authorization: Bearer {{token}}

### Criar adoção
POST {{baseURL}}/protected/adoptions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "pet_id": 1,
  "adoption_date": "2026-06-30"
}